volumes:
  db_data:
  keycloak_data:

networks:
  backend:
    internal: true
  outbound:
    internal: false

services:

  nginx:
    build: ./PFA_FRONTEND
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - outbound
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge

      # KC_HTTP_RELATIVE_PATH: /keycloak
    depends_on:
      - postgres
    command:
      - start
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    networks:
      - outbound
      - backend

  postgres:
    image: postgres:15
    environment:  
      POSTGRES_DB: ${PFA_DB_NAME}                
      POSTGRES_USER: ${PFA_DB_USER}             
      POSTGRES_PASSWORD: ${PFA_DB_PASSWORD}            
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  pfa:
    build: ./PFA_BACKEND
    container_name: pfa
    environment:
      DB_USER: ${PFA_DB_USER}            
      DB_PASSWORD: ${PFA_DB_PASSWORD}          
      DB_HOST: ${PFA_DB_HOST}            
      DB_PORT: 5432            
      DB_NAME: ${PFA_DB_NAME}        
      PFA_BACKEND_SECRET: ${PFA_BACKEND_SECRET}    
      PFA_BACKEND_CLIENT_SECRET: ${PFA_BACKEND_CLIENT_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./PFA_BACKEND:/app
    networks:
      - outbound
      - backend

