from typing import Optional, Protocol


class IBaseRepository[T](Protocol):

    async def get_all_by_user(self, user_id: int) -> list[T]: ...
    async def get_all_by_user_page(self,user_id: int, page: int, size: int) -> list[T]: ...
    async def get_count_by_user(self, user_id: int) -> int: ...
    async def get_count(self) -> int: ...
    async def get_by_id(self, entity_id: int) -> Optional[T]: ...
    async def get_all(self) -> list[T]: ...
    async def exists(self, entity_id: int) -> bool: ...
    async def add(self, entity: T) -> T: ...
    async def add_many(self, entities: list[T]) -> list[T]: ...
    async def update(self, entity: T) -> T: ...
    async def update_by_id(self, entity_id: int, values: dict) -> None: ...
    async def delete(self, entity: T) -> None: ...
    async def delete_by_id(self, entity_id: int) -> None: ...



