"""change table namee

Revision ID: 7353478fe8e6
Revises: d206f867c9e3
Create Date: 2026-03-09 18:24:30.362679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7353478fe8e6'
down_revision: Union[str, Sequence[str], None] = 'd206f867c9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['celery_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_report_id'), 'dashboard_report', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_report_task_id'), 'dashboard_report', ['task_id'], unique=False)
    op.drop_index(op.f('ix_dashboard_raport_id'), table_name='dashboard_raport')
    op.drop_index(op.f('ix_dashboard_raport_task_id'), table_name='dashboard_raport')
    op.drop_table('dashboard_raport')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_raport',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['celery_task.task_id'], name=op.f('dashboard_raport_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_raport_pkey'))
    )
    op.create_index(op.f('ix_dashboard_raport_task_id'), 'dashboard_raport', ['task_id'], unique=False)
    op.create_index(op.f('ix_dashboard_raport_id'), 'dashboard_raport', ['id'], unique=False)
    op.drop_index(op.f('ix_dashboard_report_task_id'), table_name='dashboard_report')
    op.drop_index(op.f('ix_dashboard_report_id'), table_name='dashboard_report')
    op.drop_table('dashboard_report')
    # ### end Alembic commands ###
