"""change table column expense from price to amount

Revision ID: 8674a773a6aa
Revises: c61179faa392
Create Date: 2026-02-22 12:34:43.471010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8674a773a6aa'
down_revision: Union[str, Sequence[str], None] = 'c61179faa392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "price",
        new_column_name="amount"
    )

def downgrade():
    op.alter_column(
        "expenses",
        "amount",
        new_column_name="price"
    )
