"""change type from int to str in dashboardraport task_id

Revision ID: d206f867c9e3
Revises: 473613e6c895
Create Date: 2026-03-08 13:26:31.646260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd206f867c9e3'
down_revision: Union[str, Sequence[str], None] = '473613e6c895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'RETRY', name='task_status'), nullable=False),
    sa.Column('einfo', sa.String(length=4000), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_celery_task_id'), 'celery_task', ['id'], unique=False)
    op.create_index(op.f('ix_celery_task_user_id'), 'celery_task', ['user_id'], unique=False)
    op.create_table('dashboard_raport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['celery_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_raport_id'), 'dashboard_raport', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_raport_task_id'), 'dashboard_raport', ['task_id'], unique=False)
    op.drop_index(op.f('ix_dashboard_raport_generate_status_id'), table_name='dashboard_raport_generate_status')
    op.drop_index(op.f('ix_dashboard_raport_generate_status_user_id'), table_name='dashboard_raport_generate_status')
    op.drop_table('dashboard_raport_generate_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_raport_generate_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('dashboard_raport_generate_status_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_raport_generate_status_pkey'))
    )
    op.create_index(op.f('ix_dashboard_raport_generate_status_user_id'), 'dashboard_raport_generate_status', ['user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_raport_generate_status_id'), 'dashboard_raport_generate_status', ['id'], unique=False)
    op.drop_index(op.f('ix_dashboard_raport_task_id'), table_name='dashboard_raport')
    op.drop_index(op.f('ix_dashboard_raport_id'), table_name='dashboard_raport')
    op.drop_table('dashboard_raport')
    op.drop_index(op.f('ix_celery_task_user_id'), table_name='celery_task')
    op.drop_index(op.f('ix_celery_task_id'), table_name='celery_task')
    op.drop_table('celery_task')
    # ### end Alembic commands ###
