"""celery raport model

Revision ID: f5ebd9745d33
Revises: 8674a773a6aa
Create Date: 2026-03-05 07:53:08.593724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ebd9745d33'
down_revision: Union[str, Sequence[str], None] = '8674a773a6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_raport_generate_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_raport_generate_status_id'), 'dashboard_raport_generate_status', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_raport_generate_status_user_id'), 'dashboard_raport_generate_status', ['user_id'], unique=False)
    op.drop_index(op.f('ix_expenses_price'), table_name='expenses')
    op.create_index(op.f('ix_expenses_amount'), 'expenses', ['amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_amount'), table_name='expenses')
    op.create_index(op.f('ix_expenses_price'), 'expenses', ['amount'], unique=False)
    op.drop_index(op.f('ix_dashboard_raport_generate_status_user_id'), table_name='dashboard_raport_generate_status')
    op.drop_index(op.f('ix_dashboard_raport_generate_status_id'), table_name='dashboard_raport_generate_status')
    op.drop_table('dashboard_raport_generate_status')
    # ### end Alembic commands ###
